### ISSUE TITLE
ImportKey method has non-standard behaviour

### ISSUE THREAD

**Issue by kuhy** [Toporin/SatochipApplet#6]
The problem is in the following code snippet:
``` java
if (key_size != LENGTH_EC_FP_256)
    ISOException.throwIt(key_size);
```
This is non-standard behavior that violates `ISO7816`. For instance, when I send the following `APDU` to the card, the response will be `9000` (= command correct). However, this command is invalid (wrong length).
```
B03200002C000C900000000000000000201111111111111111111111111111111111111111111111111111111111111111
```

**Comment by Toporin** [comment]
Hi,

Thanks for raising this issue.
We are working on a patch release with various minor issues.
We will address this and keep you informed.
